spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market-manage?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver